export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "aboutTopLine",
  headline: "aboutHeadline",
  description: "aboutDescription",
  buttonLabel: "buttonLabel",
  imgStart: true,
  img: require("../../images/undraw_programming.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: false,
};

export const homeObjTwo = {
  id: "graphic-design",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "graphicTopLine",
  headline: "graphicHeadline",
  description: "graphicDescription",
  buttonLabel: "buttonLabel",
  imgStart: false,
  //img: require("../../images/baner_bałtyk_koszalin.jpg"),
  img: require("../../images/baner_baltyk_koszalin.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: false,
};

export const homeObjThree = {
  id: "film-production",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "videoTopLine",
  headline: "videoHeadline",
  description: "videoDescription",
  buttonLabel: "buttonLabel",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
  videoUrl:
    "https://www.youtube.com/watch?v=xQjq1F1qp9Y&ab_channel=JakubKosmalski",
};
